const items = [
  {
    id: "1",
    item_image: "images/img7.jpg",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    company_name: "Sport",
    item_name: "Sporty Rugged Smart Watch",
    curr_price: 1900,
    original_price: 3999,
    discount_percentage: 47.5,
    return_period: 14,
    delivery_date: "10 Oct 2023",
  },
  {
    id: "2",
    item_image: "images/img2.jpg",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    company_name: "Sport",
    item_name: "Sporty Rugged Smart Watch",
    curr_price: 1900,
    original_price: 3999,
    discount_percentage: 47.5,
    return_period: 14,
    delivery_date: "10 Oct 2023",
  },
  {
    id: "3",
    item_image: "images/img3.jpg",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    company_name: "Sport",
    item_name: "Sporty Rugged Smart Watch",
    curr_price: 1900,
    original_price: 3999,
    discount_percentage: 47.5,
    return_period: 14,
    delivery_date: "10 Oct 2023",
  },
  {
    id: "4",
    item_image: "images/img4.jpg",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    company_name: "Sport",
    item_name: "Sporty Rugged Smart Watch",
    curr_price: 1900,
    original_price: 3999,
    discount_percentage: 47.5,
    return_period: 14,
    delivery_date: "10 Oct 2023",
  },
  {
    id: "5",
    item_image: "images/img5.jpg",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    company_name: "Sport",
    item_name: "Sporty Rugged Smart Watch",
    curr_price: 1900,
    original_price: 3999,
    discount_percentage: 47.5,
    return_period: 14,
    delivery_date: "10 Oct 2023",
  },
  {
    id: "6",
    item_image: "images/img6.jpg",
    rating: {
      stars: 4.5,
      noOfReviews: 1400,
    },
    company_name: "Sport",
    item_name: "Sporty Rugged Smart Watch",
    curr_price: 1900,
    original_price: 3999,
    discount_percentage: 47.5,
    return_period: 14,
    delivery_date: "10 Oct 2023",
  },
];
